<<<<<<< HEAD
# Generated by Django 2.0.3 on 2018-04-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodsale',
            fields=[
                ('prodname', models.CharField(blank=True, db_column='prodName', max_length=50, null=True)),
                ('prodcode', models.CharField(blank=True, db_column='prodCode', max_length=20, null=True)),
                ('vendor', models.CharField(blank=True, max_length=20, null=True)),
                ('saledate', models.DateField(blank=True, db_column='saleDate', null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitcost', models.FloatField(blank=True, null=True)),
                ('totlcost', models.FloatField(blank=True, null=True)),
                ('prodsale_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prodsale',
                'managed': True,
            },
        ),
    ]
=======
# Generated by Django 2.1.dev20180215184426 on 2018-02-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodsale',
            fields=[
                ('prodname', models.CharField(blank=True, db_column='prodName', max_length=50, null=True)),
                ('prodcode', models.CharField(blank=True, db_column='prodCode', max_length=20, null=True)),
                ('vendor', models.CharField(blank=True, max_length=20, null=True)),
                ('saledate', models.DateField(blank=True, db_column='saleDate', null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unitcost', models.FloatField(blank=True, null=True)),
                ('totlcost', models.FloatField(blank=True, null=True)),
                ('prodsale_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prodsale',
                'managed': True,
            },
        ),
    ]
>>>>>>> 216a4bb38ccbaad1f656463f8a37f6a95f916389
